runtime: nodejs18
env: standard

env_variables:
  # Cloud SQL
  INSTANCE_CONNECTION_NAME: "upbeat-sunup-456113-b6:europe-west3:advcancecomputerscience-3"
  DB_USER: "postgres"
  DB_PASS: "trio@123"
  DB_NAME: "stock_data"
  # GCS bucket (must already exist or replace with your bucket)
  GCS_BUCKET: "dump_advance_data_science"

# Optionally set instance class, scaling, etc.
automatic_scaling:
  min_idle_instances: 1
